kind: pipeline
type: docker
name: default
 
trigger:
  event:
    - push

steps:
  - name: build-1
    image: openjdk
    commands:
      - cd TP1/AppCollector/src/appcollector/
      - javac AppCollector.java

  - name: build-2
    image: openjdk
    commands:
      - cd TP2/AppliDocteur/src/applidocteur/
      - javac AppliDocteur.java

- name: build-3
    image: openjdk
    commands:
      - cd TP3/appUCA/src/appuca/
      - javac AppliDocteur.java

- name: build-4
    image: openjdk
    commands:
      - cd TP4/TextEditor/src/texteditor/
      - javac TextEditor.java

#  - name: code-analysis-1
#    image: openjdk
#    commands:
#      - cd 
#    secrets: [ SECRET_SONAR_LOGIN ]
#    settings:
#      sonar_host: https://codefirst.iut.uca.fr/sonar/
#      sonar_token:
#        from_secret: SECRET_SONAR_LOGIN
#      depends_on: [ build-1 ]
