kind: pipeline
type: docker
name: default
 
trigger:
  event:
    - push

steps:
  - name: build-1
    image: openjdk
    commands:
      - cd TP1/AppliDocteur/
      - javac -d bin -sourcepath src src/applidocteur/launch/AppliDocteur.java

  - name: build-2
    image: openjdk
    commands:
      - cd TP2/AppCollector/
      - javac -d bin -sourcepath src src/appcollector/launch/AppCollector.java

  - name: build-3
    image: openjdk
    commands:
      - cd TP3/AppUCA/
      - javac -d bin -sourcepath src src/appuca/launch/AppUCA.java

  - name: build-4
    image: openjdk
    commands:
      - cd TP4/TextEditor/
      - javac -d bin -sourcepath src src/texteditor/launch/TextEditor.java
