kind: pipeline
type: docker
name: default
 
trigger:
  event:
    - push

steps:
  - name: build-1
    image: openjdk
    commands:
      - cd TP1/AppliDocteur/
      - javac -d bin -sourcepath src src/applidocteur/AppliDocteur.java

  - name: build-2
    image: openjdk
    commands:
      - cd TP2/AppCollector/
      - javac -d bin -sourcepath src src/appcollector/AppCollector.java

  - name: build-3
    image: openjdk
    commands:
      - cd TP3/AppUCA/
      - javac -d bin -sourcepath src src/appuca/AppUCA.java

  - name: build-4
    image: openjdk
    commands:
      - cd TP4/TextEditor/
      - javac -d bin -sourcepath src src/texteditor/TextEditor.java

  - name: code-analysis-1
    image: openjdk
    secrets: [SECRET_SONAR_LOGIN]
    settings:
      sonar_host: https://codefirst.iut.uca.fr/sonar/
      sonar_token:
        from_secret: SECRET_SONAR_LOGIN
      depends_on: [build-1]